### ISSUE TITLE
PHP Fatal error:  Out of memory (allocated 8501854208) (tried to allocate 20480 bytes) 

### ISSUE THREAD

**Issue by ghost** [Frederick888/php-bencode#4]
this is new issue , becuase of memory hungry code., 

```
<?php
namespace bencode;
ini_set('memory_limit', '-1'); //set memory in mb
ini_set('max_execution_time', '-1'); //unlimited

$bnode = bitem::load('scrape');
$decoded_data = $bnode->to_array();
```

this is 404 mb file
`-rw-r--r-- 1 root   root   404M Nov 15 08:52 scrape
`
and i have 9 GB memory free.

yet, i received.

```
[root@ns540545]# php test.php

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 8501854208) (tried to allocate 20480 bytes) in /usr/share/nginx/com/html/admin/updatepeers/test.php on line 7

```

i tried freeing up more memory and it went through, but still., memory usage is way high.
even for 404 mb file.

Thanks

**Comment by ghost** [comment]
now i gotta find a way to split large bencoded file into small bits. and process them.
i have 64 gig of box, but majority ram is used my mysql for innodb.

**Comment by ghost** [comment]
here is that file if you wan to test it.,
on 
http://coppersurfer.tk/

http://coppersurfer.tk/full_scrape_not_a_tracker.tar.gz

Thank you.

**Comment by Frederick888** [comment]
Please read this: https://blog.onee3.org/2016/01/php-bencode-now-supports-php-7-with-no-need-of-external-libraries/

Most PHP Bencode libraries, including `php-bencode`, require memory of approximately 20 times larger than the original file. Hence if you've got a 404MB file, you'd better allow PHP to allocate up to e.g. 12GB of memory for safety.

I cannot see any problems here. Bencode handling does not lie in the area of stream processing and a high memory consumption is expected.

**Comment by ghost** [comment]
is there known way to split bencoded file ? in small chunks ? Thanks

and this one is by far best in terms of performance bencode library out there.

**Comment by Frederick888** [comment]
First of all I don't think encodings like Bencode are suitable for storing massive amount of data. Sometimes we have relatively bigger torrent files like 10 or 20 megabytes and that's it. `php-bencode` aims to accelerate the procedure of decoding and encoding a large number of Bencode files rather than a single huge file.

Secondly, if you really need to do so, rather than using any PHP libraries, delegating the work to libraries in some other languages (e.g. C, Rust, etc.) might be a better choice since scripting languages are usually not memory-efficient.

Splitting a Bencode is apparently feasible. You can just split it at a random offset, move the pointer to the nearest end of a field, count and complete the missing `e`s, remember where you stopped, send it to a common Bencode parser, and move on to the next segment. Not that complex but I don't think the work is worth it though.

**Comment by ghost** [comment]
Thank you, i have tried standalone cpp tool, and it takes forever i.e. more than 30 minutes just to parse the file.

i guess, i ll go with 3rd approach, split file in 3-4 parts.

Thanks for great module.
